# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [feature/action]
  pull_request:
    branches: [feature/action]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.0
          cache: 'npm'

      - name: Lerna Bootstrap
        run: npx lerna bootstrap

      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        with:
          coverage-comment: true
          changes-only: false
